version: 0.0
os: linux
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root