version: 0.2

phases:
  pre_build:
    commands:
      - echo Logando no Dockerhub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo Buildando imagem em `date`
      - DOCKERHUB_REPO=my-music
      - IMAGE_TAG=latest
      - docker build -t $DOCKERHUB_REPO:$IMAGE_TAG .
      - docker tag $DOCKERHUB_REPO:$IMAGE_TAG $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo Imagem buildada em `date`. Fazendo o push para Dockerhub...
      - docker push eduardorcury:$DOCKERHUB_REPO:$IMAGE_TAG