micronaut:
  application:
    name: mymusic
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:4200
  http:
    client:
      event-loop-group: custom-event-loop
      read-timeout: 45s
  netty:
    event-loops:
      custom-event-loop:
        num-threads: 20
spotify:
  credenciais:
    client_id: ${CLIENT_ID}
    client_secret: ${CLIENT_SECRET}
  accounts:
    url: https://accounts.spotify.com
  api:
    url: https://api.spotify.com/v1