micronaut:
  application:
    name: mymusic
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://my-music-webapp.s3-website-sa-east-1.amazonaws.com
            - http://localhost:4200
  http:
    client:
      event-loop-group: custom-event-loop
      read-timeout: 25s
      connect-timeout: 25s
      follow-redirects: false
  netty:
    event-loops:
      custom-event-loop:
        num-threads: 20
spotify:
  credenciais:
    client_id: ${CLIENT_ID}
    client_secret: ${CLIENT_SECRET}
  accounts:
    url: https://accounts.spotify.com
  api:
    url: https://api.spotify.com/v1
  scopes:
    - user-read-recently-played
    - user-read-private
web:
  redirect_url: http://my-music-webapp.s3-website-sa-east-1.amazonaws.com/home