micronaut:
  application:
    name: mymusic
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:4200
  http:
    client:
      read-timeout: 30s
spotify:
  credenciais:
    client_id: ${CLIENT_ID}
    client_secret: ${CLIENT_SECRET}
  accounts:
    url: https://accounts.spotify.com
  api:
    url: https://api.spotify.com/v1